### PR TITLE
Adds nvembed model to quantization algorithm

### PR DESCRIPTION
**Pull request by bndos**
Add support for quantizing the NV-Embed model using VPTQ. Benchmarked using MTEB to evaluate performance against the `bfloat16` version. Current benchmarks are based on a single task, further testing with more meaningful retrieval tasks and parameter tuning would be interesting to explore.

Benchmarks below are provided for context only and are not part of this PR.

Batch sizes were set to `16` for `VPTQ-NVEmbed` and `4` for `bfloat16`, as these were the maximum sizes that fit on a 24GB GPU.

#### Results on a specific task in (MTEB)

| Model                 | Main Score | Evaluation Time (s) |
|-----------------------|------------|-----------------------|
| VPTQ-NVEmbed-128-1024 | 0.33361    | 753.76               |
| NV-Embed bfloat16     | 0.38469    | 874.00               |

### CODE REVIEW

**Comment by YangWang92** [comment]
Thanks for your contribution! I will mergeit into the main branch and release a new version on PyPI.

**Comment by YangWang92** [comment]
Could you please provide any additional suggestions for our VPTQ project? Are there any areas where we need to make improvements?

**Comment by bndos** [comment]
> Could you please provide any additional suggestions for our VPTQ project? Are there any areas where we need to make improvements?

As far as the algorithm is concerned, I’m still getting familiar with it and the codebase. However, one suggestion I’d make is to use the Ruff formatter (`ruff format`). I noticed that `ruff` is configured in the `pyproject.toml`, but the formatter itself isn’t being used. If this were my repo, I’d probably run `ruff format` and set up a GitHub action and pre-commit hook for `ruff check` and `ruff format`. The main advantage is avoiding formatting artifacts in PRs. Just my 2 cents! :)

**Comment by YangWang92** [comment]
Yes, indeed there are some issues with our format and my code management. I will continue to improve. Thank you!

**Pull request merged**
